.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CASTGETRC" "5" "May 2017" "castget 1.2.3" "User Commands"
.
.SH "NAME"
\fBcastgetrc\fR \- configuration file for castget
.
.SH "DESCRIPTION"
The configuration file \fB\.castgetrc\fR should be located in a user\'s home directory\. It defines the behaviour of the RSS enclosure downloader \fBcastget\fR, and in particular the list of channels it operates on\.
.
.P
The file is based on a simple key\-value format\. It consists of a channel definition for each RSS feed \fBcastget\fR should process\. A channel definition starts with a line containing a channel identifier enclosed in brackets\. The channel identifier can be freely chosen by the user and is used for all subsequent operations on the channel\. Following this are one or more key\-value pairs on the form \fBkey=value\fR that define \fBcastget\fR\'s behaviour when operating on the channel\. A channel definition ends when another channel definition is started or at the end of the file\.
.
.P
Lines beginning with a hash character (`#\') and blank lines are considered comments\. All identifiers, keys and values should be UTF\-8 encoded\.
.
.P
Key\-value pairs in a channel definition define the behaviour of \fBcastget\fR when processing the channel\. The channel definition
.
.IP "" 4
.
.nf

[fooc]
url=http://downloads\.bbc\.co\.uk/podcasts/radio4/fooc/rss\.xml
spool=/home/joe/podcasts
.
.fi
.
.IP "" 0
.
.P
for example, instructs \fBcastget\fR to use \fB/home/joe/podcasts\fR as a download directory when processing the channel \fBfooc\fR\.
.
.SH "KEYS"
.
.TP
\fBurl\fR
retrieve RSS feed from this URL\. The field is mandatory for all channel definitions\.
.
.TP
\fBspool\fR
download enclosures to this directory\.
.
.TP
\fBplaylist\fR
write the fully qualified file names of all downloaded enclosures to an m3u style playlist file with this name\.
.
.TP
\fBfilter\fR
restrict operation to items whose enclosures have names matching this regular expression\.
.
.TP
\fBid3leadartist\fR
add or overwrite the `lead artist\' (TPE1) ID3v2 tag in enclosures that support this\.
.
.TP
\fBid3contentgroup\fR
add or overwrite the `content group\' (TIT1) ID3v2 tag in enclosures that support this\.
.
.TP
\fBid3title\fR
add or overwrite the `title\' (TIT2) ID3v2 tag in enclosures that support this\.
.
.TP
\fBid3album\fR
add or overwrite the `album\' (TALB) ID3v2 tag in enclosures that support this\.
.
.TP
\fBid3contenttype\fR
add or overwrite the `content type\' (TCON) ID3v2 tag in enclosures that support this\.
.
.TP
\fBid3year\fR
add or overwrite the `year\' (TYER) ID3v2 tag in enclosures that support this\.
.
.TP
\fBid3comment\fR
add or overwrite the `comment\' (COMM) ID3v2 tag in enclosures that support this\.
.
.SH "GLOBAL CONFIGURATION"
A channel definition with the channel identifier \fB*\fR will define a global configuration affecting all channels\. The global configuration
.
.IP "" 4
.
.nf

[*]
id3contenttype=Podcast
.
.fi
.
.IP "" 0
.
.P
for example, is equivalent to adding the key\-value pair \fBid3contenttype=Podcast\fR to all other channel definitions\.
.
.P
Key\-value pairs in channel definitions override the global configuration\.
.
.SH "CHANNEL REMOVAL"
If a channel configuration is removed, the channel status remains the same so that if the channel is subsequently re\-added, any enclosures marked as already downloaded will not be downloaded again\.
.
.SH "NOTE"
The source distribution includes a sample configuration file demonstrating all supported settings\.
.
.SH "SEE ALSO"
castget(1)
.
.SH "AUTHOR"
Marius L\. Jøhndal\.
